### ISSUE TITLE
New version breaks when used with Vue CLI 4.5.12

### ISSUE THREAD

**Issue by mathiasrando** [AnWeber/vue-cli-plugin-compression#1]
First of all thank you for the great plugin.

After the upgrade we encountered an issue where our builds wouldn't go through:
` TypeError: Cannot read property 'tapPromise' of undefined`

It seems to a mismatch of webpack v4 and v5. I realize it's not up to this plugin to solve, but since the upgrade causes things to break even if you don't manually update the version, it would be nice if you could add something in the README or similar for other people who might encounter this issue.

For other people who also run into this a quick fix is to simply downgrade to 1.0.3 for now.

**Comment by AnWeber** [comment]
I overlooked that @vue/cli only supports webpack4. I have deployed a new version 1.1.1.  I wanted to test it today in my work environment, but you were unfortunately faster. Sorry.

**Comment by mathiasrando** [comment]
That was fast. I'll go ahead and give it a go and report back.

No worries. I only found out due to some CI and a few breaking test builds.

**Comment by mathiasrando** [comment]
It's all good now so I'll close the issue.

Thanks for the very fast fix 👏

**Comment by AnWeber** [comment]
You are welcome. Next time I will create a major version and pay better attention to semver.
