### ISSUE TITLE
Error: Algorithm "brotliCompress" is not found in "zlib"

### ISSUE THREAD

**Issue by karroumBen** [AnWeber/vue-cli-plugin-compression#17]
```pluginOptions: {
    compression:{
      modes: ['development', 'production'],
      brotli: {
        filename: '[file].br[query]',
        algorithm: 'brotliCompress',
        include: /\.(js|css|html|svg|json)(\?.*)?$/i,
        compressionOptions: {
          params: {
            [zlib.constants.BROTLI_PARAM_QUALITY]: 11,
          },
        },
        minRatio: 0.8,
      },
      gzip: {
        filename: '[file].gz[query]',
        algorithm: 'gzip',
        include: /\.(js|css|html|svg|json)(\?.*)?$/i,
        minRatio: 0.8,
      }
    },
  }
```

```
"vue-cli-plugin-compression": "~1.2.0",
"@vue/cli-service": "^3.0.5",
"vue": "^2.5.17",
```
My guess is this has nothing to do with the dependencies here rather the plugin is somehow updated

**Comment by AnWeber** [comment]
Since it is still configured [that way even with Webpack](https://webpack.js.org/plugins/compression-webpack-plugin/#using-brotli). Also on NodeJS the constant is still mentioned ([v18](https://nodejs.org/api/zlib.html), [v16](https://nodejs.org/dist/latest-v16.x/docs/api/zlib.html))., I just don't see the problem. For me locally it still works with NodeJS v16.17.0. Is your `@vue/cli-service` really a 3 year old version and what NodeJS Version are you using?

```
 "vue": "^3.0.0"
 "@vue/cli-service": "~4.5.0",
 "vue-cli-plugin-compression": "~1.2.0",
```

**Comment by karroumBen** [comment]
I am using node version v14.19.3

**Comment by AnWeber** [comment]
v14 also supports the constant (https://nodejs.org/docs/latest-v14.x/api/zlib.html). Could you provide an example project?

**Comment by karroumBen** [comment]
@AnWeber does version 10 have support for the constant? in the server the version used is v10.

**Comment by AnWeber** [comment]
@karroumBen It is mentioned but I think not. Most brotli methods are added in v11.7 (https://nodejs.org/docs/latest-v14.x/api/zlib.html#zlib_zlib_brotlicompress_buffer_options_callback). 
But I would advise you to update NodeJS if you can somehow or not run this publicly. The versions are really old.

**Comment by karroumBen** [comment]
@AnWeber thank you for the support.I will try updating the version in the server.

**Comment by AnWeber** [comment]
@karroumBen Node 10.16 and later supports Brotli. Maybe you just need a small update (https://webpack.js.org/plugins/compression-webpack-plugin/#using-brotli)
