### ISSUE TITLE
ReferenceError: zlib is not defined

### ISSUE THREAD

**Issue by thorrak** [AnWeber/vue-cli-plugin-compression#4]
When attempting to build after installing & configuring as directed, I get the following error:
``` 
ERROR  ReferenceError: zlib is not defined
ReferenceError: zlib is not defined
    at Object.<anonymous> (/Users/thorrak/WebstormProjects/vue_project/vue.config.js:14:26)
```

The referenced line is: 
`[zlib.constants.BROTLI_PARAM_QUALITY]: 11,`

The issue is fixed by adding `const zlib = require("zlib");` to the top of vue.config.js -- I'll submit a PR shortly incorporating the fix into the documentation

**Comment by AnWeber** [comment]
Thank you. I have not tested zlib and relied on the example of webpack-plugin-compression
