### ISSUE TITLE
Impossible to invoke this extension in dev environment

### ISSUE THREAD

**Issue by jingkaimori** [AnWeber/vue-cli-plugin-compression#6]
Suggest a config entry to explicitly enable it rather than infer from `NODE_ENV`

**Comment by AnWeber** [comment]
Changing it with a custom switch like `forceDev` would be possible, but I don`t see what advantage this would bring. I would have tested it just now, but the Webpack Dev Server does not deliver compressed files.
But there should be no downside to including the feature either. So there is nothing directly against it.

**Comment by AnWeber** [comment]
is changed with v1.2.0
